### ISSUE TITLE
Inaccessible Variables

### ISSUE THREAD

**Issue by inkDaemonNine13** [trehoffman/fedex-api-vb.net#1]
When I add this class to my project, I get many access errors such as: 'ConfigurationManager' is not declared. It may be inaccessible due to its protection. I tried making the partial class public, but it had no effect. I also tried importing System.Configuration, but it had no effect. Screenshots attached.
![fedex1](https://user-images.githubusercontent.com/4299643/52281808-db890280-292c-11e9-936e-896d348f36a4.PNG)
![fedex2](https://user-images.githubusercontent.com/4299643/52281816-ddeb5c80-292c-11e9-8c4d-52263c8dcb86.PNG)

**Comment by trehoffman** [comment]
Let's start with the ConfigurationManager class:

In your project, you should be able to add a reference.  Add "System.Configuration" and that should clear that up.

If possible, share your project and I can take a more in-depth look.

**Comment by inkDaemonNine13** [comment]
Thanks for the reply. I have already added the reference to System.Configuration. But just to test, I removed it and added it again with no change. My project is very simple. Just a form with a textbox and a button to send a tracking number to this class and get xml back.

**Comment by trehoffman** [comment]
Without seeing your project it is difficult for me to say why the ConfigurationManager class isn't being resolved.

I just added a project solution to the repository, so you can try running that and see what differences you might see between my repository and your code.

**Comment by inkDaemonNine13** [comment]
Your solution works perfectly. I will have to go through and find what you did differently. I could be that I'm trying to add just the class itself to my old project. Maybe I need to start fresh?

**Comment by trehoffman** [comment]
It's tough to say.

Is your project a website, desktop, or other kind of application?

**Comment by inkDaemonNine13** [comment]
Desktop app. Thanks again for the help. I'll play around with it a little more and then get back with you.

**Comment by trehoffman** [comment]
That might be the discrepancy.  My project is a website, and the ConfigurationManager class is being used to look into the "web.config" file for certain variables.  You might have to replace those calls with something else for desktop, or just cut out those calls completely and hard-code what you need.
